version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb+srv://arpan:arpan7838@userlogin.nggbtqi.mongodb.net/?retryWrites=true&w=majority&appName=userlogin

  compiler:
    build: ./compiler
    ports:
      - "5001:5001"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb+srv://arpan:arpan7838@userlogin.nggbtqi.mongodb.net/?retryWrites=true&w=majority&appName=userlogin

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
